[tox]
requires = tox-uv
envlist =
    lint,
    py{310,311,312,313,314},docs

[testenv]
runner = uv-venv-lock-runner
dependency_groups = tests
commands =
    pytest --cov=flask_smorest --cov-branch --cov-report=term-missing --cov-report=xml {posargs}

[testenv:lint]
dependency_groups = lint
skip_install = true
commands = pre-commit run --all-files --show-diff-on-failure

[testenv:docs]
dependency_groups = docs
commands = sphinx-build --fresh-env docs/ docs/_build {posargs}

; Below tasks are for development only (not run in CI)

[testenv:docs-serve]
runner = uv-venv-runner
deps = sphinx-autobuild
dependency_groups = docs
commands = sphinx-autobuild --port=0 --open-browser --delay=2 docs/ docs/_build {posargs} --watch src --watch README.rst

[testenv:readme-serve]
runner = uv-venv-runner
deps = restview
skip_install = true
commands = restview README.rst
